### ISSUE TITLE
Supabase not working in gradio python space

### ISSUE THREAD

**Issue by UNNAMMEDUSER** [supabase/supabase-py#1071]
Supabase not working in gradio python space in Hugging face

Error log:
```
Exit code: 1. Reason: Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
```
```
===== Application Startup at 2024-12-16 17:28:42 =====

Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
```

**Comment by Hallidayo** [comment]
Hi, I've moved this issue over from the supabase repo as it seems to be related to supabase-py

**Comment by grdsdev** [comment]
Hi @loganpearce17 the error in logs is `supabase._sync.client.SupabaseException: Invalid URL`, make sure you're using a valid project URL.

**Comment by loganpearce17** [comment]
Hi, I'm not sure why the response isn't showing up here (maybe it wasn't carried over from the migration), but they told me to update my sdk to 5.18.0 and that resolved the issue. The project URL was already valid.

**Comment by grdsdev** [comment]
It seems this is working on updated version of gradio, so I'm closing this issue.
